### ISSUE TITLE
Error with second-level domain

### ISSUE THREAD

**Issue by pm2036** [Rbeuque74/letsencrypt-ovh-hook#2]
Hello,
There is an issue with second level domain like `*.asso.fr`, `*.com.fr`, `*.co.uk`, `*.eu.org` ....

For example for: `monasso.asso.fr`
The pattern doesn't match well and consider that the domain is `asso.fr` and the subdomain `monasso`, but, its wrong and for the ovh api, the domain is `monasso.asso.fr` and the api report the error
`ovh.exceptions.ResourceNotFoundError: This service does not exist`

Best regards

**Comment by rbeuque74** [comment]
Hello,
Yes, I will look into adding a coverage for that case.

Thanks for the report, will reply to this thread with fix in order you can test it :)

Romain

**Comment by wxdlabs** [comment]
Hello,

the problem is still exists in my case. For example for domains like `something.net.pl` or `something.org.pl` the OVH API reports `ovh.exceptions.ResourceNotFoundError: This service does not exist`. Could you resolve the issue?

Best regards

**Comment by rbeuque74** [comment]
Hello @wxdlabs ,
The code has been fixed to find the closest domain in the OVH API.
Are you sure the configuration on dehydrated side is correct regarding the domain zone you have on OVHcloud side ?

If yes, I might be able to look at your case if you can provide me the X-OVH-QUERYID header that will contain traces to be investigated.

Romain

**Comment by wxdlabs** [comment]
Hello @rbeuque74,

I think, my configuration is correct. I've been used it before. The problem was appear when I try to deploy wildcard SSL certificate for second-level domain (with dehydrated client).
Could you help me, how can I provide you X-OVH-QUERYID header?

Best regards
